# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
  
      - name: Get npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Building step
        env: # as an environment variable
          super_secret: ${{ secrets.SuperSecret }}
          REACT_APP_RUNNING_AT: ${{ secrets.REACT_APP_RUNNING_AT }}
          REACT_APP_FACEBOOK_APP_ID: ${{ secrets.REACT_APP_FACEBOOK_APP_ID }}
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_DATABASE_URL: ${{ secrets.REACT_APP_FIREBASE_DATABASE_URL }}
          REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.REACT_APP_FIREBASE_APP_ID }}
          REACT_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.REACT_APP_FIREBASE_MEASUREMENT_ID }}
          REACT_APP_GLOBAL_SETTINGS_SITE_NAME: ${{ secrets.REACT_APP_GLOBAL_SETTINGS_SITE_NAME }}
          REACT_APP_GLOBAL_SETTINGS_TWITTER_USERNAME: ${{ secrets.REACT_APP_GLOBAL_SETTINGS_TWITTER_USERNAME }}
          REACT_APP_GLOBAL_SETTINGS_DOMAIN_URI: ${{ secrets.REACT_APP_GLOBAL_SETTINGS_DOMAIN_URI }}
          REACT_APP_COVID19_REGIONS_AROUND: ${{ secrets.REACT_APP_COVID19_REGIONS_AROUND }}
          REACT_APP_GOV_BR_URI: ${{ secrets.REACT_APP_GOV_BR_URI }}
          REACT_APP_GOV_BR_APP_ID: ${{ secrets.REACT_APP_GOV_BR_APP_ID }}
          REACT_APP_ALGOLIA_APP_ID: ${{ secrets.REACT_APP_ALGOLIA_APP_ID }}
          REACT_APP_ALGOLIA_SEARCH_API_KEY: ${{ secrets.REACT_APP_ALGOLIA_SEARCH_API_KEY }}
        run: |
         npm ci
         npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: .next # The folder the action should deploy.
